CONTRIBUTING.md
README.md

Updates the IRC links to point to freenode so users don't need to create accounts.
Changes in README.md and CONTRIBUTING.md only.
NA
This was a suggestion by @RandyLevensalor 
NA
- Have you connected this PR to the issue it fixes? Yes.
- Does the documentation need an update? No (this does it).
- Does this add new Python dependencies? No.

Updated IRC links

---

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md

Adds the `PULL_REQUEST_TEMPLATE.md` file and updates the `CONTIRBUTING.md` file with info about the pull request template. The goal is to make PRs look like this one.
No.
See the `PULL_REQUEST_TEMPLATE.md` and `CONTIRBUTING.md` files.
This began as a suggestion from @missbikesalot. Thank you!
NA
- Have you connected this PR to the issue it resolves? Yes.
- Does the documentation need an update? No (this does it).
- Does this add new Python dependencies? No.
- Have you added unit or functional tests for this PR? No.

Added PULL_REQUEST_TEMPLATE.md

---

snaps-openstack/ansible_p/ansible_utils/ansible_configuration.py
snaps-openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/kolla_set_pin.yaml
snaps-openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_controller_pike.yaml
snaps-openstack/conf/openstack/kolla/deployment.yaml
snaps-openstack/packages/source/inventory/multinode

This PR has the fixes for issue 53-CPU pinning. 
NA
A reviewer can verify this PR by deploying OpenStack with values in deployment.yaml:
Eg. 
isolcpus: "0-15"
reserved_host_memory_mb: "16384"
OpenStack deployment should be successful now(task "TASK [nova.conf changes]"
should not get failed)
NA
NA
Yes
No
No
OpenStack deployment needs to be performed.

Issue 53-CPU pinning fixes

---

doc/source/install/install.md
snaps-openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_controller_pike.yaml
snaps-openstack/provision/openstack/plugin/Kolla_impl/Kolla_utils.py

This PR has the fixes for the support of Ceph and for the removal of dynamically generated files after the deployment of OpenStack.
No
A reviewer needs to add ceph in deployment.yaml file and can verify this PR by deploying OpenStack.
NA
NA
This PR will also resolve issue #62 
Yes
No
OpenStack deployment needs to be performed.

Kolla pike ceph

---

doc/source/install/install.md

Fixes a couple glaing TENNANT typos. And adds more info the vxlan setting.
None, Totally cosmetic in the install.md
Look at the diff.
Tennant with three Ns is annoying. Tenant with two is much preferred.
I didn't open an issue, just fixing.
This is the documentation, so DONE.
No.
No.

Minor typo cleanup

---

snaps-openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/setup_kolla.yaml
snaps-openstack/packages/source/build.py
snaps-openstack/packages/source/test_build.py

This PR will resolve the issue of pushing images.
NA
By deploying OpenStack.
NA
NA
#77 
NA
NA
OpenStack deployment needs to be performed.

patch for insecure_registry

---

doc/source/install/install.md
snaps-openstack/ansible_p/ansible_utils/ansible_configuration.py
snaps-openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/kolla_set_pin.yaml
snaps-openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_controller_pike.yaml
snaps-openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/remove_images.yaml
snaps-openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/remove_registry.yaml
snaps-openstack/provision/openstack/plugin/Kolla_impl/Kolla_utils.py

Includes the fixes for the issue of MTU size not getting reflected.
This also includes the optional param for the PULL_HUB changes.
No
By deploying openstack successfully
No
NA
NA
Yes
No
OpenStack deployment has to be performed.

Changes for MTU

---

ci/README.md
ci/playbooks/deploy_os.yaml
ci/playbooks/run_tests.yaml
ci/snaps/snaps_os_tmplt.yaml
snaps-openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_compute_pike.yaml
snaps-openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_controller_pike.yaml

Fix a bug in an ansible playbook and adds a playbook to execute snaps-oo tests.
no
It won't break anything but they could execute the snaps_os_tmplt.yaml with the snaps-oo launcher
CI
yes
later
no
the purpose of this is to add testing

Ansible fix and addition of playbook for executing snaps-oo tests.

---

ci/playbooks/templates/deployment.yaml.tmplt

Fixing issue to address compatabilty change.
Fixes issue with new deployment.yaml model.
No.
Run a CI install.
Another PR broke the CI scripts.
Issue #112 
No.
No.
No...this is the test.

Adding second disk configration to deployment template file

---

doc/source/install/install.md
network_config.py
snaps_openstack/ansible_p/ansible_utils/ansible_configuration.py
snaps_openstack/utilities/network_utils.py
snaps_openstack/utilities/playbooks/vlan_cleanup_playbook.yaml
snaps_openstack/utilities/playbooks/vlan_playbook.yaml
snaps_openstack/utilities/var.yaml

his will enable support of multiple VLAN on single NIC, - along with Review comments of pull request  #110  Incorporated 
Also, this PR contains minor changes for multidisk ceph deployment
no
by deploying OpenStack and configuring a range of VLAN Ids on the physical network
no
NA
#104 
Yes
No
No

Kolla vlan Review Comments incorporated

---

iaas_launch.py
snaps_openstack/ansible_p/ansible_utils/ansible_configuration.py

Add missing target ip for storage clean-up to succeed
No
Run clean-up option for deployment
This was introduced when adding multiple ceph disk support
N/A
#121 
No
No
No, use existing integration tests.

Fixed missing target ip during storage clean-up

---

snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_compute_newton.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_compute_pike.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_controller_newton.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_controller_pike.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/setup_kolla.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/single_node_kolla_newton.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/single_node_kolla_pike.yaml

Fixes various typos.
No.
Run snaps-openstack deploy.
No.
N/A
#58 and #61 
No
No
No

Fixes various typos in #58 and #61

---

snaps_openstack/utilities/playbooks/physical_mtu.yaml

Fixes mtu reconfig script to be compatible with ansible version older than 2.3
No
Run mtu reconfig script.
No
#140 
No
No
No, uses existing tests.

Fixes #140

---

conf/openstack/kolla/deployment.yaml
doc/source/install/install.md
snaps_openstack/ansible_p/ansible_utils/ansible_configuration.py
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/cleanup_hosts.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/kolla_set_pin.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/kolla_sethosts.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_compute_pike.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_controller_pike.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/setup_kolla.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/setup_registry.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/single_node_kolla_pike.yaml
snaps_openstack/packages/source/globals_bak.yml
snaps_openstack/packages/source/kolla-build.conf
snaps_openstack/packages/source/ml2_conf.ini
snaps_openstack/provision/openstack/plugin/kolla_impl/kolla_utils.py

This pull request enables dpdk support in kolla-openstack
No
by deploying snaps-openstack
N/A
yes

Kolla pike dpdk

---

snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_controller_pike.yaml

Defines the hugepages properties to large in all flavors
No
By deploying the Openstack and creating DPDK VMs
No
No
No
No
No
No

changes for dpdk

---

doc/source/install/install.md

Add a step for re-deployment after clean-up.
No
Follow the steps re-deploying snaps-openstack after clean-up.
No
N/A
#148 
Yes, done in this PR.
No
No need
No

Fixes #148

---

doc/source/install/install.md

inform user to update the metadata of flavour for enabling DPDK VM
No
NA
NA
NA
Issue #149 
Yes
No
NA
NA

Changes in install.md

---

ci/playbooks/deploy_os.yaml
ci/snaps/snaps_os_tmplt.yaml

Use the full patch for the directory in CI instead of a relative path.
no
run CI
Nope.  Just tidying the code.
No issue, just a small change.
No.
No
No
No

Use the full patch for the directory in CI

---

ci/playbooks/deploy_os.yaml
ci/snaps/snaps_os_tmplt.yaml

These changes should fix CI
Fixes and speeds up CI scripts.
No.
Run CI.
Additional changes needed for using absolute instead of relative paths.
No
No
no
no
Need to confirm env files

Adjusting path and using standard name for ubuntu image

---

snaps_openstack/ansible_p/ansible_utils/ansible_configuration.py
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/kolla_sethosts.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_controller.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_iso_network.yaml
snaps_openstack/provision/openstack/deployment.py

Fixes typos and changes some wording.
No
Run CI script
No
N/A
#164 
No
No
No
No

Fixes #164

---

snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_compute.yaml
snaps_openstack/ansible_p/commission/openstack/playbooks/deploy_mode/kolla/multinode_kolla_controller.yaml
snaps_openstack/provision/openstack/plugin/kolla_impl/kolla_utils.py

This PR provides support of overlay2 storage driver
No
By deploying OpenStack
No
NA
#184 
No
No
No
No

Support of overlay2 storage driver

---

setup.py
snaps_openstack/ansible_p/ansible_utils/ansible_playbook_launcher.py

Makes snaps-openstack to work with ansible > 2.4
Testing with other versions different than 2.7.2 of ansible
Install ansible 2.7 and run

Changes for compatibility with Ansible > 2.4, fixes for #211
